markdown: redcarpet
pygments: true
paginate: 8

safe:  false
# Site settings
title: 北漂IT民工
description: Just another Jekyll theme design and code by zhanxin.info.
keywords: Jekyll Theme
url: http://pizn.github.io/kunka
feed: /atom.xml
favicon: http://jekyllrb.com/favicon.png
#Nav config
nav:
  - text: 首页
    url: /index.html
  - text: 分类目录 
    url: /categories.html
  - text: 文章归档
    url: /archives.html
  - text: 联系我
    url: /contact.html
  - text: 友情链接
    url: /links.html
#Author config
author:
    name: 北漂IT民工
    email: calidion@gmail.com
    
    
    imageLink: http://tp2.sinaimg.cn/1832671293/180/40020872447/1
    simpleIntro: 我是「展新展新」，一个矛盾体的化身，在你的掌心里。
    detailIntro:
      <p>Jekyll 是一个简洁的、特别针对博客平台的 静态网站 生成器。它使用一个模板目录作为网站布局的基础框架，并在其上运行 Textile 、 Markdown 或 Liquid 标记语言的转换器，最终生成一个完整的静态Web站点，可以被放置在Apache或者你喜欢的其他任何Web服务器上。它同时也是 GitHub Pages 、一个由 GitHub 提供的用于托管项目主页或博客的服务，在后台所运行的引擎。</p>
      <p>很早之前，使用过 wordpress 来写博客。但是还要处理很多的底层问题。而使用 Jekyll 来写博客，可以很简单，写 Markdown 就好。然而，Jekyll 还很年轻，没有很多主题的支持。这里的主题，就是为 Jekyll 而写的。希望你能喜欢。</p>
    description: > # this means to ignore newlines until "baseurl:"
  关于IT技术的新闻，技术，感悟，交流，分享
baseurl: "/wordpress" # the subpath of your site, e.g. /blog/
url: "http://www.3gcnbeta.com/" # the base hostname & protocol for your site
twitter_username: htc3000
github_username:  calidion

paginate: 10
paginate_path: "blogs/page/:num"

# Build settings
markdown: kramdown
