safe:  false
# Site settings
title: 北漂IT民工
keywords: 北漂IT民工,Web,javascript,HTML,HTTP,W3C,Mysql,Sails
feed: /atom.xml
favicon: http://jekyllrb.com/favicon.png
url: ""

#Nav config
nav:
  - text: 首页
    url: /index.html
  - text: 分类目录 
    url: /categories.html
  - text: 文章归档
    url: /archives.html
  - text: 关于
    url: /about.html

#Author config
author:
    name: 北漂IT民工
    email: calidion@gmail.com
    imageLink: http://tp4.sinaimg.cn/2344087443/180/5622386331/1
    simpleIntro: 关注IT技术的新闻，技术，感悟，交流，分享。
    detailIntro:
    qqQun:
      - name: 高级前端开发框架群
        no: 288791858
      - name: Vim用户群
        no: 40964276
      - name: 互联网架构师群
        no: 40935408
      - name: PhoneGap移动技术研究群
        no: 238035953


baseurl: "" # the subpath of your site, e.g. /blog/

#Follow me, you can choose your icon by http://fortawesome.github.io/Font-Awesome/icons/#brand
follow:
  - class: icon-rss
    url: /atom.xml
  - class: icon-weibo
    url: http://weibo.com/3gcnbeta
  - class: icon-renren
    url: http://renren.com
  - class: icon-github-alt
    url: http://github.com/calidion
  - class: icon-twitter
    url: http://twitter.com/htc3000
  - class: icon-google-plus
    url: http://google.com

#Links
customLinks:
  - item:
    - text: 北漂IT民工
      url: http://www.3gcnbeta.com/wordpress
    - text: Jekyll
      url: http://jekyllrb.com
    - text: 校长的博客
      url: http://phped.sinaapp.com/
    message: 好友
  - item:
    - text: sailsjs
      url: http://sailsjs.org
    - text: Google Font
      url: http://www.google.com/fonts/
    - text: jQuery
      url: http://jquery.com/
    message: 其他相关链接

#googleAnaly, your id link UA-12345678-X
googleAnaly:
  config: true
  id: UA-11293547-1

#comment config
disqus:
  config: false
  id: piznblog

duoshuo:
  config: true
  id: 3gcnbeta

twitter_username: htc3000
github_username:  calidion

permalink: /:year/:month/:day/:title/
paginate: 10
paginate_path: "blogs/page/:num"

# Build settings
markdown: kramdown
kramdown:
  input: GFM
highlighter: pygments
